#!/bin/sh

set -o errexit
set -o nounset


celery \
    --app=django_structlog_demo_project.taskapp \
    --broker="${CELERY_BROKER_URL}" \
    flower \
    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
