import structlog


def inject_context_dict(_, __, event_dict):
    """
    Add the structlog context dict to log events generated by the stdlib logging library.
    """
    context_class = structlog.get_config().get("context_class")

    if context_class:
        for key, value in context_class().items():
            if key not in event_dict:
                event_dict[key] = value

    return event_dict
